name = "Arcana"
license = "Creative Commons Attribution 3.0 Unported"
licenselink = "https://creativecommons.org/licenses/by/3.0/"
description = "A Hugo port of the HTML5 UP Arcana template"

homepage = "https://github.com/half-duplex/hugo-arcana"
demosite = "https://sec.gd/hugo/themes/arcana/"

tags = ["blog","business","html5up","responsive"]
features = ["blog"]

[author]
  name = "Trevor Bergeron"
  homepage = "https://sec.gd/"

[original]
  name = "@ajlkn"
  homepage = "https://html5up.net/"
