[params]
    description = "Eine responsive Webseiten-Vorlage im Business- und Unternehmensstil."
    show_post_dates = false

    [params.footer]

        [[params.footer.links]]
            header = "Links"
        [[params.footer.links.links]]
            title = "Mattis et quis rutrum"
            url = "#"
        [[params.footer.links.links]]
            title = "Suspendisse amet varius"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum accumsan dolor"
            url = "#"
        [[params.footer.links.links]]
            title = "Mattis rutrum accumsan"
            url = "#"
        [[params.footer.links.links]]
            title = "Suspendisse varius nibh"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus mattis"
            url = "#"

        [[params.footer.links]]
            header = "Noch mehr Links"
        [[params.footer.links.links]]
            title = "Duis neque nisi dapibus"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum accumsan sed"
            url = "#"
        [[params.footer.links.links]]
            title = "Mattis et sed accumsan"
            url = "#"
        [[params.footer.links.links]]
            title = "Duis neque nisi sed"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum amet varius"
            url = "#"

        [params.footer.contact_form]
            enabled = true
            header = "Kontakt aufnehmen"
            action = ""
